app:
  app_id: '0'

dock:
  address:
    host: 'localhost'
    port: '1453'

router:
  min_router_chain: 3
  min_search: 3
  ttl: 10
  periodical_gossip_interval: 60
  route_path: 'route.yaml'
  max_ttl: 40

GNN:
  base_path: '/root'
  model_path: 'model/graph_sage.tf'
  algorithm: 'graphSAGE'
  auto_switch: True
  max_peer_number: 100
  graphSAGE:
    hidden_dims: [128, 7]
    sample_size: [10, 10]
    input_dim: 1433
    output_dim: 7
    batch_size: 32
    epochs: 20

chain_manager:
  base_path: '/root'
  chain:
    island_0:
      type: 'island'
      abci_port: '2665'
      rpc_port: '2663'
      p2p_port: '2664'
      join: False
      persistent_peers:
        - host: 'localhost'
          port: '2663'
    lane_0:
      type: 'lane'
      abci_port: '2668'
      rpc_port: '2666'
      p2p_port: '2667'
      join: False
      persistent_peers:
        - host: 'localhost'
          port: '2666'
    lane_1:
      type: 'lane'
      abci_port: '2671'
      rpc_port: '2669'
      p2p_port: '2670'
      join: False
      persistent_peers:
        - host: 'localhost'
          port: '2669'
    lane_2:
      type: 'lane'
      abci_port: '2674'
      rpc_port: '2672'
      p2p_port: '2673'
      join: False
      persistent_peers:
        - host: 'localhost'
          port: '2672'
