dock:
  address:
    host: 'localhost'
    port: '1453'

router:
  min_router_chain: 3
  min_search: 3
  ttl: 10
  route_path: 'route.yaml'

GNN:
  algorithm: 'graphSAGE'
  auto_switch: True
  max_peer_number: 100
  graphSAGE:
    hidden_dims: [128, 7]
    sample_size: [10, 10]
    input_dim: 1433
    batch_size: 32
    epochs: 20

chain_manager:
  island:
    base_path: '/root'
    number: 1
    abci_port: ['2665']
    rpc_port: ['2663']
    p2p_port: ['2664']
  lane:
    base_path: '/root'
    number: 3
    abci_port: ['2668', '2671', '2674']
    rpc_port: ['2666', '2669', '2672']
    p2p_port: ['2667', '2670', '2673']

join:
  chain_type: 'lane'
  base_path: '/root'
  port:
    abci: '2677'
    rpc: '2675'
    p2p: '2676'
  persistent_peers: ['ID@HOST:PORT', '']

